/* eslint-disable import/no-mutable-exports */
import { store } from '@store';

export let Color = {
  transparents: 'transparent',
  white: 'white',
  black: 'black',
  green: 'green',
  red: 'red',
  yellow: 'yellow',
  blue: 'blue',
  gray: 'gray',
  transparent: 'rgba(52, 52, 52, 0.4)',
  transparent_camera: 'rgba(52, 52, 52, 0.5)',
  base_color: '#0056D2',
  text_color: '#0F172A',
  text_color_hover: '#64748B',
  color_unactive: '#3A4865',
  cl_background_dialog: 'rgba(248,228,184,0.5)',
  background_dialog_loading: '#00000050',
  cl_border_text_input: '#B4BAC8',
  cl_text_requied: '#f0827a',
  cl_requied_input: '#f0827a',
  cl_text_place_holder: '#B4BAC8',
  cl_button_switch: '#FD7A59',
  cl_button_custom: '#FD7A59',
  placeholderTextColor: '#B4BAC8',
  bg_buttom_sheet: 'rgba(244, 228, 184, 0.5)',
  cl_text_app: '#3A4865',
  cl_text_home: '#607D8B',
  bg_profile: '#E5E5E5',
  cl_shadow_profile: 'rgba(58, 72, 101, 0.08)',
  bg_cm_button: '#FD7A59',
  cl_text_input: '#3A4865',
  cl_border_unactive: 'rgba(253, 122, 89, 0.2);',
  cl_border_active: '#FD7A59',
  cl_dash_unactive: '#B4BAC8',
  cl_bg_payment: '#F4E4B8',
  cl_border_input: '#B4BAC8',
  cl_text_description: '#677187',
  cl_text_title: '#3A4865',
  cl_border_check: '#7099EF',
  cl_text_order_id: '#413D3E',
  cl_active_point: '#65845A',
  cl_bg_item: '#edebea',
  cl_border_estimate: '#84CA2D',
  bg_area_driver: 'rgba(223, 150, 39, 0.15)',
  bg_cl_order_history: 'rgba(180, 186, 200, 0.5)',
  cl_text_label: '#3A4865',
  cl_line_type: '#E3ECF0',
  cl_bg_bottom_type: 'rgba(156, 163, 178, 0.5)',
  bg_buttom_call: 'rgba(156, 163, 178, 0.3)',
  cl_bg_footer_check_out: '#f9eee3',
  cl_text_money: '#67B731',
  cl_border_errand_type_1: '#667696',
  cl_border_errand_type_2: '#AFCCA4',
  background_dialog: 'rgba(58, 72, 101, 0.5)',
  cl_background_guest: '#B4BAC8',
  cl_text_mes: '#293C5E',
  cl_background_btn_withdraw: '#3A4865',
  cl_border_filter: '#CADAE1',
  cl_border_item_category: '#FD7A59',
  cl_item_product: '#FFF5F2',
  primary: '#202c41',
  cl_background_dialog_warn: '#25252599',
  color_bg_item_home: '#EDF5FF',
  color_text_item: '#475569',
  color_bg_progress_bar: '#F1F5F9',
  color_progress_bar: '#F9AA00',
  color_text_progress_bar: '#94A3B8',
  color_width_featured_class: '#E2E8F0',
  color_bg_featured_class: '#F1F5F9',
  color_bg_tab_view: '#F9F9F9',
  color_bg_item_my_test: '#CAE7FC',
  color_border: '#F1F5F9',
  color_pass: '#23AA26',
  color_not_pass: '#F4462C',
  color_border_answer: '#94A3B8',
  color_check_answer: '#0153FF',
  color_uncheck_answer: '#CBD5E1',
  color_yellow_bm: '#FBC53E',
  color_gray_bm: '#EAECF0',
  color_yellow_NotSubmit_exercise: '#D68B00',
  color_white_education_program: '#f2f2f2',
  color_red_education_program: '#ff4081',
  color_purple_education_program: '#673ab7',
  color_text_content: '#242736',
  color_text_shadow: '#000000',
  color_shadow: '#dee0df',
  color_bg_image_profile: '#2472E3',
  color_bg_item_profile: '#0550BB',
  color_message_toast_success: '#28a745',
  color_message_toast_warning: '#ffc107',
  color_header_title: '#27272A',
  color_home_background: '#f5f6f5',
  color_active_tab_view: '#444',
};

export const getColor = async (appColor) => {
  let colorSetting = appColor;
  if (!appColor) {
    colorSetting = store.getState().global?.appColor;
  }
  Color = {
    transparents: 'transparent',
    white: 'white',
    black: 'black',
    green: 'green',
    red: 'red',
    yellow: 'yellow',
    blue: 'blue',
    gray: 'gray',
    transparent: 'rgba(52, 52, 52, 0.4)',
    transparent_camera: 'rgba(52, 52, 52, 0.5)',
    base_color: colorSetting?.base_color ?? '#0056D2',
    text_color: colorSetting?.text_color ?? '#0F172A',
    text_color_hover: colorSetting?.text_color_hover ?? '#64748B',
    color_unactive: colorSetting?.color_unactive ?? '#3A4865',
    cl_background_dialog: colorSetting?.cl_background_dialog ?? 'rgba(248,228,184,0.5)',
    background_dialog_loading: colorSetting?.background_dialog_loading ?? '#00000050',
    cl_border_text_input: colorSetting?.cl_border_text_input ?? '#B4BAC8',
    cl_text_requied: colorSetting?.cl_text_requied ?? '#f0827a',
    cl_requied_input: colorSetting?.cl_requied_input ?? '#f0827a',
    cl_text_place_holder: colorSetting?.cl_text_place_holder ?? '#B4BAC8',
    cl_button_switch: colorSetting?.cl_button_switch ?? '#FD7A59',
    cl_button_custom: colorSetting?.cl_button_custom ?? '#FD7A59',
    placeholderTextColor: colorSetting?.placeholderTextColor ?? '#B4BAC8',
    bg_buttom_sheet: colorSetting?.bg_buttom_sheet ?? 'rgba(244, 228, 184, 0.5)',
    cl_text_app: colorSetting?.cl_text_app ?? '#3A4865',
    cl_text_home: colorSetting?.cl_text_home ?? '#607D8B',
    bg_profile: colorSetting?.bg_profile ?? '#E5E5E5',
    cl_shadow_profile: colorSetting?.cl_shadow_profile ?? 'rgba(58, 72, 101, 0.08)',
    bg_cm_button: colorSetting?.bg_cm_button ?? '#FD7A59',
    cl_text_input: colorSetting?.cl_text_input ?? '#3A4865',
    cl_border_unactive: colorSetting?.cl_border_unactive ?? 'rgba(253, 122, 89, 0.2);',
    cl_border_active: colorSetting?.cl_border_active ?? '#FD7A59',
    cl_dash_unactive: colorSetting?.cl_dash_unactive ?? '#B4BAC8',
    cl_bg_payment: colorSetting?.cl_bg_payment ?? '#F4E4B8',
    cl_border_input: colorSetting?.cl_border_input ?? '#B4BAC8',
    cl_text_description: colorSetting?.cl_text_description ?? '#677187',
    cl_text_title: colorSetting?.cl_text_title ?? '#3A4865',
    cl_border_check: colorSetting?.cl_border_check ?? '#7099EF',
    cl_text_order_id: colorSetting?.cl_text_order_id ?? '#413D3E',
    cl_active_point: colorSetting?.cl_active_point ?? '#65845A',
    cl_bg_item: colorSetting?.cl_bg_item ?? '#edebea',
    cl_border_estimate: colorSetting?.cl_border_estimate ?? '#84CA2D',
    bg_area_driver: colorSetting?.bg_area_driver ?? 'rgba(223, 150, 39, 0.15)',
    bg_cl_order_history: colorSetting?.bg_cl_order_history ?? 'rgba(180, 186, 200, 0.5)',
    cl_text_label: colorSetting?.cl_text_label ?? '#3A4865',
    cl_line_type: colorSetting?.cl_line_type ?? '#E3ECF0',
    cl_bg_bottom_type: colorSetting?.cl_bg_bottom_type ?? 'rgba(156, 163, 178, 0.5)',
    bg_buttom_call: colorSetting?.bg_buttom_call ?? 'rgba(156, 163, 178, 0.3)',
    cl_bg_footer_check_out: colorSetting?.cl_bg_footer_check_out ?? '#f9eee3',
    cl_text_money: colorSetting?.cl_text_money ?? '#67B731',
    cl_border_errand_type_1: colorSetting?.cl_border_errand_type_1 ?? '#667696',
    cl_border_errand_type_2: colorSetting?.cl_border_errand_type_2 ?? '#AFCCA4',
    background_dialog: colorSetting?.background_dialog ?? 'rgba(58, 72, 101, 0.5)',
    cl_background_guest: colorSetting?.cl_background_guest ?? '#B4BAC8',
    cl_text_mes: colorSetting?.cl_text_mes ?? '#293C5E',
    cl_background_btn_withdraw: colorSetting?.cl_background_btn_withdraw ?? '#3A4865',
    cl_border_filter: colorSetting?.cl_border_filter ?? '#CADAE1',
    cl_border_item_category: colorSetting?.cl_border_item_category ?? '#FD7A59',
    cl_item_product: colorSetting?.cl_item_product ?? '#FFF5F2',
    primary: colorSetting?.primary ?? '#202c41',
    cl_background_dialog_warn: colorSetting?.cl_background_dialog_warn ?? '#25252599',
    color_bg_item_home: colorSetting?.color_bg_item_home ?? '#EDF5FF',
    color_text_item: colorSetting?.color_text_item ?? '#475569',
    color_bg_progress_bar: colorSetting?.color_bg_progress_bar ?? '#F1F5F9',
    color_progress_bar: colorSetting?.color_progress_bar ?? '#F9AA00',
    color_text_progress_bar: colorSetting?.color_text_progress_bar ?? '#94A3B8',
    color_width_featured_class: colorSetting?.color_width_featured_class ?? '#E2E8F0',
    color_bg_featured_class: colorSetting?.color_bg_featured_class ?? '#F1F5F9',
    color_bg_tab_view: colorSetting?.color_bg_tab_view ?? '#F9F9F9',
    color_bg_item_my_test: colorSetting?.color_bg_item_my_test ?? '#CAE7FC',
    color_border: colorSetting?.color_border ?? '#F1F5F9',
    color_pass: colorSetting?.color_pass ?? '#23AA26',
    color_not_pass: colorSetting?.color_not_pass ?? '#F4462C',
    color_border_answer: colorSetting?.color_border_answer ?? '#94A3B8',
    color_check_answer: colorSetting?.color_check_answer ?? '#0153FF',
    color_uncheck_answer: colorSetting?.color_uncheck_answer ?? '#CBD5E1',
    color_yellow_bm: colorSetting?.color_yellow_bm ?? '#FBC53E',
    color_gray_bm: colorSetting?.color_gray_bm ?? '#EAECF0',
    color_yellow_NotSubmit_exercise: colorSetting?.color_yellow_NotSubmit_exercise ?? '#D68B00',
    color_white_education_program: colorSetting?.color_white_education_program ?? '#f2f2f2',
    color_red_education_program: colorSetting?.color_red_education_program ?? '#ff4081',
    color_purple_education_program: colorSetting?.color_purple_education_program ?? '#673ab7',
    color_text_content: colorSetting?.color_text_content ?? '#242736',
    color_text_shadow: colorSetting?.color_text_shadow ?? '#000000',
    color_shadow: colorSetting?.color_shadow ?? '#dee0df',
    color_bg_image_profile: colorSetting?.color_bg_image_profile ?? '#2472E3',
    color_bg_item_profile: colorSetting?.color_bg_item_profile ?? '#0550BB',
    color_message_toast_success: colorSetting?.color_message_toast_success ?? '#28a745',
    color_message_toast_warning: colorSetting?.color_message_toast_warning ?? '#ffc107',
    color_header_title: colorSetting?.color_header_title ?? '#27272A',
    color_home_background: colorSetting?.color_home_background ?? '#f5f6f5',
    color_active_tab_view: colorSetting?.color_active_tab_view ?? '#444',
  };
};
